interface CustomerLogin { 
	product_id: number,
	product_core: string,
	product_name: string,
	bar_code: string,
	brand_id: number,
	one_category_id: number,
	two_category_id: number,
	three_category_id: number,
	supplier_id: number,
	price: ,
	average_cost: ,
	publish_status: number,
	audit_status: number,
	weight: ,
	length: ,
	height: ,
	width: ,
	color_type: ,
	production_date: ,
	shelf_life: number,
	descript: ,
	indate: Date,
	modified_time: Date,
}