interface orderMaster {
	orderId: number,
	orderSn: number,
	customerId: number,
	shippingUser: string,
	province: number,
	city: number,
	district: number,
	address: string,
	paymentMethod: number,
	orderMoney: number,
	districtMoney?: number,
	shippingMoney?: number,
	paymentMoney?: number,
	shippingCompName?: string,
	shippingSn?: string,
	createTime?: Date,
	shippingTime?: Date,
	payTime?: Date,
	receiveTime?: Date,
	orderStatus?: number,
	orderPoint?: number,
	invoiceTime?: string,
	modifiedTime?: Date,
}
